#!/bin/sh

# Show the total size of all the files in the trashcan.
if [ -z $TRASH ]; then
	echo "Environment variable TRASH is not set yet!"
	echo "Please add the following varibale to .bash_profile or .profile or .login at the ~/ directory: "
	echo "TRASH=~/.trash/"
else
        if [ ! -e "$TRASH" ]; then
                mkdir "$TRASH"
        fi
	du -s -h "$TRASH"
fi
