#!/bin/sh
#
# Lss. A wrapper for the ls command except for arugments -s, -g, -i, which lists the file information from the directory given to the command (directories are treated as file unless explicitly list all the files in them).

options=""
file=false
for i in "$@"
do
	# Options
	if [[ $i == -* ]]; then
		# Assert invalid options
		if [ "$i" == "-s" -o "$i" == "-g" -o "$i" == "-i" ]; then
			echo "$0: Invalid option -- $i"
			exit 1
		fi
	else
		# If not options, must be filename
		file=true
	fi
done

# If arguments contain filename, then put them all to the ls
if [ $file == true ]; then
	ls -d -l -S "$@"
else
	# If no filename, then ls current directory
	ls -l -S "$@"
fi

