#!/bin/sh

# Remove all the files in the trashcan.
if [ $# -ge 1 ]; then
        echo "$0: Cannot have any arguments!"
        exit 1
fi
if [ -z $TRASH ]; then
	echo "Environment variable TRASH is not set yet!"
	echo "Please add the following varibale to .bash_profile or .profile or .login at the ~/ directory: "
	echo "export TRASH=~/.trash/"
else
        if [ ! -e "$TRASH" ]; then
                mkdir "$TRASH"
        fi
	rm -r "$TRASH"*
fi
