#!/bin/sh

# List all the files in the trashbin.
if [ -z $TRASH ]; then
	echo "Environment variable TRASH is not set yet!"
	echo "Please add the following varibale to .bash_profile or .profile or .login at the ~/ directory: "
	echo "export TRASH=~/.trash/"
else
	if [ ! -e "$TRASH" ]; then
		mkdir $TRASH
	fi
	ls -l -L "$TRASH"
fi
