#!/bin/sh

# Remove the files given to the command to the trashcan.
#TRASH=~/.trash
if [ -z "$TRASH" ]; then
	echo "Environment variable TRASH is not set yet!"
	echo "Please add the following varibale to .bash_profile or .profile or .login at the ~/ directory: "
	echo "export TRASH=~/.trash/"
else
	if [ ! -e $TRASH ]; then
		mkdir $TRASH
		echo "Created $TRASH"
	fi
	for i in "$@"
	do
		cur_dir=`pwd "$i"`/
		if [ -e "$TRASH.$i" ]; then
			rm "$i"
		else
			mv "$i" ".$i"
			ln -s "$cur_dir.$i" "$TRASH$i"
		fi
	done
fi
